model:
  name: "mistral7b-sj-weather"
  pretrained: "mistralai/Mistral-7B-v0.1"
  use_lora: true

training:
  checkpoint_dir: "C:\\Users\\Ken Zhang\\Git\\weather-prediction-model\\llms\\checkpoints\\mistral7b"
  batch_size: 1
  grad_acc_steps: 4
  epochs: 3
  learning_rate: 2e-5

lora:
  r: 8
  alpha: 32
  dropout: 0.1
  target_modules:
    - q_proj
    - v_proj
